name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mtools
      run: sudo apt-get install mtools
    - name: make
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: os.img
        path: os.img
